import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Header from './components/Header'
import Container from './components/Container'
import Footer from './components/Footer'
import ReactQueryProvider from './components/ReactQueryProvider'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '400', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ReactQueryProvider>
          <Header />
          <Container>{children}</Container>
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  )
}
